image: node:8.6.0

test:
  script:
  - npm install
  - npm run test

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install
  - npm run build
  artifacts:
    paths:
    - public
  only:
    - master
