image: node:4.2.2

test:
  script:
  - npm install
  - npm run test

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install
  - npm install webpack -g
  - webpack
  artifacts:
    paths:
    - public
  only:
    - master
