image: node:10.12.0

test:
  script:
    - npm install
    - npm run test

lint:
  script:
    - npm install
    - npm run lint

pages:
  cache:
    paths:
      - node_modules/

  script:
    - npm install
    - npm run build
    - du -hs public/*
    - grep -o version.* public/index.html
    - ls
  artifacts:
    paths:
      - public
  only:
    - master
