const ServiceWorkerMessages = {};
ServiceWorkerMessages.REFRESH_DATABASE = "REFRESH_DATABASE";
ServiceWorkerMessages.REFRESH_DATABASE_PROGRESS_REPORT = "REFRESH_DATABASE_PROGRESS_REPORT";
ServiceWorkerMessages.REFRESH_DATABASE_COMPLETED = "REFRESH_DATABASE_COMPLETED";

export {ServiceWorkerMessages};